name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # 배포 대상 브랜치
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ###### 프로젝트 구조에 맞게 아래 설정을 수정하세요 ######
          app_location: "/src" # 소스 코드 위치
          api_location: ""  # Azure Functions 등 API가 없다면 비워둠
          output_location: "/" # 빌드 결과물 폴더 (예: dist, build)
          skip_app_build: true  #일반 HTML, CSS 및 JavaScript 파일을 배포하는 경우 빌드 단계가 실제로 필요하지 않습니다. 

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepr
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
